<a href="https://colab.research.google.com/github/Luiz-Adami/aula_html5_css3/blob/main/C%C3%B3pia_de_Curso_de_Python_para_iniciantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Olá Mundo
Nosso primeiro comando em python

In [ ]:
print("Olá Mundo")

Olá Mundo


###Strings
Concatenação com o operador +

In [ ]:
print("Curso" + " de Python")

Curso de Python


Substituindo valores com format ( )

In [ ]:
print("Aula {} do curso de {}" .format(1, "Python"))


Aula 1 do curso de Python


Transformando para minúsculas com  lower( ) 

In [ ]:
print("Curso de Python para Iniciantes" .lower())

curso de python para iniciantes


Transformando para maiúsculas com upper

In [ ]:
print("Curso de Python para Iniciantes" .upper())

CURSO DE PYTHON PARA INICIANTES


Removendo espaços em branco com  strip() 

In [ ]:
print("   Curso de Python para Iniciantes   " .strip())

Curso de Python para Iniciantes


     O tipo str

In [ ]:
type("Curso de Python para Iniciantes")

str

###Lidando com números e Operadores Matemáticos

Tipos Numéricos

In [ ]:
type(2)

int

In [ ]:
type(2.5)

float

    Soma

In [ ]:
2 + 2

4

Subtração

In [ ]:
10 - 7

3

    Multiplicação

In [ ]:
7 * 3

21

  Exponenciação

In [ ]:
5 ** 2

25

  Divisão

In [ ]:
5 / 2

2.5

In [ ]:
type(5/2)

float

  Divisão Inteira

In [ ]:
5 // 2

2

  Resto da Divisão

In [ ]:
5 % 2

1

  Expressões

In [ ]:
10 - 5 + 20 -4

21

In [ ]:
((2+3)*(4-2)) ** 2

100

###Variáveis
      Variáveis de texto

In [ ]:
texto = "Curso de Python para Iniciantes"
texto

'Curso de Python para Iniciantes'

In [ ]:
texto = texto + " - Aula 02"
texto

'Curso de Python para Iniciantes - Aula 02'

    Variáveis numéricas

In [ ]:
soma = 0
soma

0

      Incrementando / Decrementando

In [ ]:
soma = soma + 1
soma

1

In [ ]:
soma += 1
soma

2

In [ ]:
soma -= 1
soma

1

In [ ]:
soma = soma - 1
soma

0

###Lista
   criando e selecionando elementos
   

In [ ]:
frutas = ['maca', 'banana', 'laranja']
frutas

['maca', 'banana', 'laranja']

In [ ]:
frutas[2]

'laranja'

In [ ]:
numeros = [1,2,3,4,5]
numeros

[1, 2, 3, 4, 5]

In [ ]:
lista = ['a', 'b', 'c', frutas, numeros]
lista

['a', 'b', 'c', ['maca', 'banana', 'laranja'], [1, 2, 3, 4, 5]]

In [ ]:
lista[4]

[1, 2, 3, 4, 5]

In [ ]:
lista[3][0]

'maca'

In [ ]:
lista[:2]

['a', 'b']

In [ ]:
lista[2:]

['c', ['maca', 'banana', 'laranja'], [1, 2, 3, 4, 5]]

In [ ]:
lista[2:4]

['c', ['maca', 'banana', 'laranja']]

   adicionando e removendo elementos

In [ ]:
frutas.append('goiaba')
frutas

['maca', 'banana', 'laranja', 'goiaba']

In [ ]:
frutas.pop()
frutas

['maca', 'banana', 'laranja']

In [ ]:
frutas.pop(0)
frutas

['banana', 'laranja']

   Alterando Elementos

In [ ]:
frutas[0] = 'pera'
frutas

['pera', 'banana', 'laranja']

   Tuplas

In [ ]:
marcas = 'gm', 'ford', 'fiat', 'vw'
marcas

('gm', 'ford', 'fiat', 'vw')

In [ ]:
marcas[3]


'vw'

   A diferença principal entre listas e tuplas é que os elementos de tuplas não podem ser alterados.

In [ ]:
marcas[0] = 'ferrari'

TypeError: ignored

###Dicionários

In [ ]:
notas = {'portugues': 8, 'ingles': 7.4, 'matematica': 9}
notas

{'ingles': 7.4, 'matematica': 9, 'portugues': 8}

In [ ]:
pessoa = {'nome': 'Joao', 'idade': 25, 'profissao': 'pintor'}
pessoa

{'idade': 25, 'nome': 'Joao', 'profissao': 'pintor'}

In [ ]:
times = {1: 'Flamengo', 2: 'Sao Paulo', 3:'Gremio'}
times

{1: 'Flamengo', 2: 'Sao Paulo', 3: 'Gremio'}

   Selecionando Elementos

In [ ]:
notas['matematica']

10

In [ ]:
pessoa['nome']

'Joao'

In [ ]:
times[2]

'Sao Paulo'

   Alterando Elementos

In [ ]:
notas['matematica'] = 10
notas

{'ingles': 7.4, 'matematica': 10, 'portugues': 8}

In [ ]:
times[2] = 'Palmeiras'
times

{1: 'Flamengo', 2: 'Palmeiras', 3: 'Gremio'}

   Adicionando Elementos

In [ ]:
notas['geografia'] = 7.1
notas

{'geografia': 7.1, 'ingles': 7.4, 'matematica': 10, 'portugues': 8}

In [ ]:
times[85] = 'Vasco'
times

{1: 'Flamengo', 2: 'Palmeiras', 3: 'Gremio', 85: 'Vasco'}

###IF / ELSE

In [ ]:
x = 1
y = 5

   Operadores Lógicos

In [ ]:
x == 1

True

In [ ]:
x == 2

False

In [ ]:
x < 0

False

In [ ]:
x >= 0

True

In [ ]:
x != 0

True

In [ ]:
(x > 0) and (y < 2)

False

In [ ]:
(x > 0) or (y < 2)

True

   Identação Obrigatória

In [ ]:
x = 0
if (x > 0):
  print('x é maior que zero')
else:
  print('x é menor ou igual a zero')

x é menor ou igual a zero


In [ ]:
x = 0
if (x > 0):
  print('x é maior que zero')
 print('Oi') 
else:
  print('x é menor ou igual a zero')

IndentationError: ignored

In [ ]:
x = 0
if (x > 0):
  print('x é maior que zero')
elif(x == 0):
  print('x é zero')
else:
  print('x é menor')

x é zero


###FOR

In [ ]:
contador = [0,1,2,3,4,5,6,7,8,9]
contador

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for valor in contador:
  print(valor)

0
1
2
3
4
5
6
7
8
9


In [ ]:
range?

In [ ]:
for valor in range(10):
  print(valor)


0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(4,18,2):
  print(i)


4
6
8
10
12
14
16


In [ ]:
cidades = ['São Paulo', 'Brasilia', 'Curitiba']
cidades

['São Paulo', 'Brasilia', 'Curitiba']

In [ ]:
for cidade in cidades:
  print('Já morei em ' + cidade)


Já morei em São Paulo
Já morei em Brasilia
Já morei em Curitiba


In [ ]:
minha_lista = [1,2,3,'cachorro', 'gato', 'papagaio']
minha_lista

[1, 2, 3, 'cachorro', 'gato', 'papagaio']

In [ ]:
for cada_item in minha_lista:
  print(cada_item)

1
2
3
cachorro
gato
papagaio


###WHILE

In [ ]:
x = 0
while x < 5:
  print(x)
  x = x + 1

0
1
2
3
4


###List Comprehensions

In [ ]:
quadrados = []
for numero in range(10):
  quadrados.append(numero**2)

quadrados

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

   Uma maneira mais concisa de criar listas

In [ ]:
quad = [numero**2 for numero in range(10)]
quad

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

###Funções
   

   Função que não retorna valor

In [ ]:
def exibir_mensagem(parametro):
  print('Mensagem: ' +parametro)

In [ ]:
exibir_mensagem(' Olá!!!')

Mensagem:  Olá!!!


In [ ]:
def exibir_dados(nome, idade):
  print('Meu nome é {} ' .format(nome))
  print('Tenho {} anos.' .format(idade))

In [ ]:
exibir_dados('Maria', 70)

Meu nome é Maria 
Tenho 70 anos.


In [ ]:
exibir_dados('Paulo', 12)

Meu nome é Paulo 
Tenho 12 anos.


   Função que retorna valor

In [ ]:
def elevar_ao_quadrado(numero):
  return numero**2

In [ ]:
elevar_ao_quadrado(2)

4

In [ ]:
elevar_ao_quadrado(25)

625

###Bibliotecas
   Já instaladas no ambiente (Google Colab)

In [ ]:
import numpy

In [ ]:
numpy.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
import numpy as np

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
from numpy import ones

In [ ]:
ones(5)

array([1., 1., 1., 1., 1.])

   Instalando Bibliotecas Externas

In [ ]:
!pip install yfinance

In [ ]:
import yfinance as yf

In [ ]:
yf.download('^BVSP')

[*********************100%***********************]  1 of 1 completed


Open           High  ...      Adj Close    Volume
Date                                      ...                         
1993-04-27      24.799999      25.400000  ...      24.500000         0
1993-04-28      24.500000      24.600000  ...      24.299999         0
1993-04-29      24.299999      24.799999  ...      23.700001         0
1993-04-30      23.700001      24.200001  ...      24.100000         0
1993-05-03      24.100000      24.400000  ...      24.100000         0
...                   ...            ...  ...            ...       ...
2021-10-05  110397.000000  111691.000000  ...  110458.000000  10379000
2021-10-06  110454.000000  110614.000000  ...  110560.000000  13279200
2021-10-07  110563.000000  111522.000000  ...  110585.000000  10646000
2021-10-08  110586.000000  114172.000000  ...  112833.000000  12871400
2021-10-11  112834.000000  113982.000000  ...  112180.000000  10283700

[7028 rows x 6 columns]